name: sotasum

channels:
  - pytorch
  - conda-forge
  - nvidia

dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - faiss-cpu
  - pip
  - notebook
  - ipywidgets
  - pip:
      - pytorch-lightning[extra]
      - mlflow
      - tensorboard
      - deepspeed
      - fairscale
      - transformers<4.23.0
      - datasets
      - evaluate
      - pandas
      - gdown
      - httpx
      - matplotlib
      - nltk
      - rouge-score
      - rich
      - pymsteams
      - tensorboard
